import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import walletRouter from "./wallet";
import circlesRouter from "./circles";
import goalsRouter from "./goals";
import learnRouter from "./learn";
import activityRouter from "./activity";
import notificationsRouter from "./notifications";
import profileRouter from "./profile";
import storageRouter from "./storage";
import passkeysRouter from "./passkeys";
import securityRouter from "./security";
import accountRouter from "./account";
import operationsRouter from "./operations";
import streaksRouter from "./streaks";
import onchainRouter from "./onchain";
import referralRouter from "./referral";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(walletRouter);
router.use(circlesRouter);
router.use(goalsRouter);
router.use(learnRouter);
router.use(activityRouter);
router.use(notificationsRouter);
router.use(profileRouter);
router.use(storageRouter);
router.use(passkeysRouter);
router.use(securityRouter);
router.use(accountRouter);
router.use(operationsRouter);
router.use(streaksRouter);
router.use(onchainRouter);
router.use(referralRouter);

export default router;
