// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-redesign/CenteredFocus.tsx": () => import("../components/mockups/login-redesign/CenteredFocus.tsx"),
  "./components/mockups/login-redesign/ImmersiveBrand.tsx": () => import("../components/mockups/login-redesign/ImmersiveBrand.tsx"),
  "./components/mockups/login-redesign/SocialProofMomentum.tsx": () => import("../components/mockups/login-redesign/SocialProofMomentum.tsx")
};
